    export const data = [
        {
            id: 1,
            name : 'Pumpkin Patchwork Tote Bag Blue',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777758/ButtercupBurrow/pumpkin_bag_blue_lypdui.jpg',
            price: '$60.00',
            description: 'Quilted pumpkin tote bag with sky blue background',
        },
        {
            id: 2,
            name : 'Pumpkin Patchwork Tote Bag Green',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777759/ButtercupBurrow/pumpkin_bag_green_ttaadd.jpg',
            price: '$60.00',
            description: 'Quilted pumpkin tote bag with sage green background',
        },
        {
            id: 3,
            name : 'Patchwork Bunny Tote Bag',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777739/ButtercupBurrow/brown_bunny_bag_front_bexkwp.jpg',
            price: '$60.00',
            description: 'Quilted brown rabbit tote bag with blue background',
        }, 
        {
            id: 4,
            name : 'Patchwork Sheep Tote Bag',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777758/ButtercupBurrow/sheep_front_and_back_xkqyel.jpg',
            price: '$60.00',
            description: 'Quilted brown rabbit tote bag with blue background',
        }, 
        {
            id: 5,
            name : 'Patchwork Sheep Tote Bag',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777758/ButtercupBurrow/sheep_bag_v2_front_and_back_csl6dt.jpg',
            price: '$60.00',
            description: 'Quilted sheep tote bag with brown background',
        }, 
        {
            id: 6,
            name : 'Patchwork Cat and Dog Tote Bag',
            countInStock: '0',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777678/ButtercupBurrow/83034AD0-9104-469A-84F5-5A704E0C9831_jl2tzl.jpg',
            price: '$65.00',
            description: 'Cat and Dog Micro Quilt Tote Bag',
        }, 
        {
            id: 7,
            name : 'Patchwork Block Tote Bag',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777739/ButtercupBurrow/3_in_block_bag_front_yav41a.jpg',
            price: '$60.00',
            description: 'Quilted patchwork tote bag',
        }, 
        {
            id: 8,
            name : 'Rabbit Linocut Print',
            countInStock: '11',
            category: 'linocut prints',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777661/ButtercupBurrow/bunny_print_maqmy0.jpg',
            price: '$10.00',
            description: 'Linocut print art',
        },
        {
            id: 9,
            name : 'Black Cat Patchwork Wall Decor',
            countInStock: '1',
            category: 'wall hangings',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777661/ButtercupBurrow/black_cat_wall_hanging_zicsvo.jpg',
            price: '$60.00',
            description: 'Quilted patchwork tote bag',
        },
        {
            id: 10,
            name : 'Snoozing Fox Patchwork Wall Decor',
            countInStock: '1',
            category: 'wall hangings',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777662/ButtercupBurrow/fox_wall_hanging_vyjwqt.jpg',
            price: '$40.00',
            description: 'Micro quilt fox wall hanging',
        },
        {
            id: 11,
            name : 'Hopping Bunny Patchwork Wall Decor',
            countInStock: '1',
            category: 'wall hangings',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777661/ButtercupBurrow/bunny_wall_hanging_hcaosd.jpg',
            price: '$50.00',
            description: 'Micro quilt bunny wall hanging',
        },
        {
            id: 12,
            name : 'Rainbow Pride Tote Bag',
            countInStock: '1',
            category: 'tote bags',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777678/ButtercupBurrow/IMG_1886_rzixbs.jpg',
            price: '$45.00',
            description: 'Quilted pride tote bag',
        },
        {
            id: 13,
            name : 'Micro Quilt Bunny Wall Decor',
            countInStock: '1',
            category: 'wall hangings',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777680/ButtercupBurrow/IMG_1902_baqryt.jpg',
            price: '$40.00',
            description: 'Micro quilt bunny wall hanging',
        },
        {
            id: 14,
            name : 'Bunny Baby Blanket Quilt- Pink Colorway',
            countInStock: '0',
            category: 'quilts',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777661/ButtercupBurrow/bunny_baby_blanket_pink_dsoisn.jpg',
            price: '$120.00',
            description: 'Bunny baby blanket sized quilt, pink version',
        },
        {
            id: 15,
            name : 'Bunny Baby Blanket Quilt- Primary Colorway',
            countInStock: '0',
            category: 'quilts',
            image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777662/ButtercupBurrow/IMG_9812_hqjhxx.jpg',
            price: '$120.00',
            description: 'Bunny baby blanket sized quilt, pink version',
        },
        // {
        //     id: 15,
        //     name : 'Patchwork Block Tote Bag',
        //     slug: 'block-tote-patchwork',
        //     category: 'tote bag',
        //     image: '',
        //     price: '60.00 USD',
        //     description: 'Quilted patchwork tote bag',
        // },
        // {
        //     id: 16,
        //     name : 'Patchwork Block Tote Bag',
        //     slug: 'block-tote-patchwork',
        //     category: 'tote bag',
        //     image: '',
        //     price: '60.00 USD',
        //     description: 'Quilted patchwork tote bag',
        // },
        // {
        //     id: 17,
        //     name : 'Patchwork Block Tote Bag',
        //     slug: 'block-tote-patchwork',
        //     category: 'tote bag',
        //     image: '',
        //     price: '60.00 USD',
        //     description: 'Quilted patchwork tote bag',
        // },
    ];

    export const categories = [
            {
                id: 1,
                name : 'tote bags',
                slug: 'tote-bags',
                image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670781237/ButtercupBurrow/91A2E7D6-C2A2-494E-95E1-508DA214A909_1_201_a_hmmaui.jpg',
            },
            {
                id: 2,
                name : 'linocut prints',
                slug: 'linocut-prints',
                image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777664/ButtercupBurrow/bunny_print_framed_xu48pj.jpg',
            },
            {
                id: 3,
                name : 'quilts',
                slug: 'quilts',
                image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777710/ButtercupBurrow/luna_dzgjhn.jpg',
            },  
            {
                id: 4,
                name : 'wall hangings',
                slug: 'wall-hangings',
                image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777661/ButtercupBurrow/black_cat_wall_hanging_zicsvo.jpg',
            },
            {
                id: 4,
                name : 'new items',
                slug: 'new-items',
                image: 'https://res.cloudinary.com/djfedr7vl/image/upload/v1670777661/ButtercupBurrow/black_cat_wall_hanging_zicsvo.jpg',
            },
            {
                id: 5,
                name : 'clearance',
                slug: 'clearance',
                image: 'https://www.canva.com/design/DAFUrt547BE/f9vylQGZgV2TrCCJvzAfbQ/view?utm_content=DAFUrt547BE&utm_campaign=designshare&utm_medium=link&utm_source=viewer',
            },
        ];
